### ISSUE TITLE
Mob incompatibility SCP Lockdown mod

### ISSUE THREAD

**Issue by deadspidervenom** [Laike-Endaril/Dynamic-Stealth#57]
So I know for Sure SCP 173 is having issues with the New ai

For reference if you dont know about SCP 173 IF you look at him he is not supposed to be moving, but when you look away/blink he will move.

With your mod installed the moment he sees you he runs to you, and instant kills you.

**Comment by deadspidervenom** [comment]
Oh also a incompatibility with mobs from the Sanity Mod

**Comment by Laike-Endaril** [comment]
Thanks for the report(s), I'll download SCP Lockdown and Sanity and take a look when I get a chance.

Just fyi though, I've been super busy elsewhere lately, so I don't have an ETA right now

**Comment by Laike-Endaril** [comment]
Egad, I'm half asleep...

I forgot to mention the workaround.  Go to DS settings...
(server settings -> threat system -> entity-specific settings -> threat bypass)

Add the registry names of those entities to that list, and you'll *probably* be good to go.

If you need to find the registry names, go to the main folder for the modpack, and go to
config/fantasticlib/reference/entities.txt
for a listing of all entities in your pack.  You'll have to search it for likely names.

**Comment by deadspidervenom** [comment]
KK ty, as for when you get a chance it NP, TY for your help on the matter, Regardless of how long it takes. You are the first dev to reply that you would be wiling to work in something. (even if it takes a while)

**Comment by Laike-Endaril** [comment]
Np, tell me how the threat bypass works out if you try it...as that may end up being the official solution (depending).  Basically if I don't find a better solution, I'd just be adding entries for those mobs to the default threat bypass configs

**Comment by Laike-Endaril** [comment]
If you have any other particular SCP mob issues, tell me and I'll look at them.

I haven't noticed any sanity mobs spawn so far, even though I'm "insane"...is that what you meant?  Ie. they don't even spawn for some reason?

**Comment by Laike-Endaril** [comment]
After further testing, sanity mobs seem to be spawning and working just fine; they're just extremely rare occurrences.  I think I have the spawn rates for all of them maxed in the configs, and it still took a long time for a light seeker to spawn...

In any case, if you have more SCP stuff, go ahead and post it here and I'll take a look

If you've had some other issue with sanity mobs, maybe post those in a separate issue, with more detail

Otherwise, I'm considering this one fixed in next version for now

**Comment by Laike-Endaril** [comment]
The sculpture should be fixed in the latest release if you use the new default threat bypass settings, and the ghost zombie should be more noticeable if you use the new default "naturally bright" settings (it doesn't make the mob glow; it just makes the mob fully visible in darkness)

**Comment by deadspidervenom** [comment]
Sorry for the lack of reply, i sorta got out of it for a while.

Also it still broken because you used the incorrect entity id, its 

entity.scp.killer_statue

not 

scp.killer_statue

**Comment by Laike-Endaril** [comment]
I just double-checked, and in the most recent version of SCP Lockdown on curseforge, and it is indeed 
`scp.killer_statue`

As seen in the auto-populated entities file:
`config/fantasticlib/reference/entities.txt`
(Which populates when you run the game, pulling data directly from the Forge entity registry)

If you're using a different version of SCP Lockdown, the entity may have a different registry name, in which case you'll have to put it in manually

**Comment by deadspidervenom** [comment]
I use the latest version, when tested without the entity. it acted the same. When i add the entity. it ignores 173 and 173 works like it should.

I found the entity name in the .lang file. also i double checked with /summon

**Comment by Laike-Endaril** [comment]
That sounds very odd...I'll recheck the behavior on my end

**Comment by Laike-Endaril** [comment]
Ah, it is not `scp.killer_statue`
It is `scp:killer_statue`
(With a colon, not a period)
I can confirm this is working; the entity outline correctly appears black, and the statue chases you down if you face away from it *and it is facing you* (I decided not to give it soul sight in the default settings, so it does need to be facing you)

Side note: I tried these, but none of them worked:
`entity.scp.killer_statue`
`entity.scp:killer_statue`
`entity:scp:killer_statue`

I also double checked using the summon command, and it auto-completes for `scp:killer_statue`, but not for any of the other 3 (in fact, there are no entries starting with "entity").

There is a possibility that a difference in forge version or some nasty core mod is having an effect on forge registry naming usages in-game.  All of my tests are run on forge 1.12.2 stable (1.12.2 - 14.23.5.2768)

What forge version are you running atm?

Also, could you post your current SCP jar somewhere so I can download and test the literal same jar you're currently using, just in case?

**Comment by Laike-Endaril** [comment]
Closing this one for now due to lack of response; can look into it again if I get some of the requested info (actually an archive of the entire modpack, including the forge install would be optimal)
